version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - pushgateway

  grafana:
    image: grafana/grafana:10.1.5
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana_provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana_dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  pgdata:
